name: Build and Package Randomizer

on:
  push:
    branches: '**'
    paths: 
      - 'Randomizer/**'
      - '.github/**'
  pull_request:
    branches: '**'
    paths: 
      - 'Randomizer/**'
      - '.github/**'
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration (Debug/Release)'
        required: false
        default: 'Debug'
        options:
        - Release
        - Debug

jobs:
  build:
    runs-on: windows-latest
    env:
      CONFIGURATION: ${{ github.event.inputs.configuration || 'Debug' }} # For PRs and commits

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Prepare Build Variables
      shell: bash
      run: |
        VERSION=$(grep '^  Version' Randomizer/everest.yaml | cut -d' ' -f 4)

        if [[ "$CONFIGURATION" == "Release" ]]; then
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
        else
          echo "VERSION=${VERSION}-devbuild" >> $GITHUB_ENV
        fi

        BUILD_DIR="Randomizer/bin/$CONFIGURATION"
        echo "BUILD_DIR=${BUILD_DIR}" >> $GITHUB_ENV

    - name: Build Randomizer
      shell: bash
      env:
        CONFIGURATION: ${{ env.CONFIGURATION }}
      run: |
        mkdir -p dist
        dotnet build -c ${CONFIGURATION}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Randomizer_${{ env.VERSION }}
        path: ${{ env.BUILD_DIR }}